services:

  nemesida:
    image: nemesida/nwaf-dyn-ce
    platform: linux/amd64
    volumes:
      - ./nemesida/waf-config/:/nginx.configs
    ports:
      - 8081:80

  echoserver:
    image: traefik/whoami
    # ports:
    #   - 8082:80

  bench:
    image: wallarm/gotestwaf
    volumes:
      - ./reports:/app/reports
    profiles:
      - donotstart

# docker compose run bench --url=http://modesec --noEmailReport
#
# touch nemesida/waf-config/first-launch
# docker compose run nemesida
